repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [
          pytest,
          types-beautifulsoup4,
          types-Pygments,
          types-PyYAML, 
          types-requests,
        ]
        files: .
  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: pytest tests/
        language: python
        additional_dependencies: [".[dev]"]
        pass_filenames: false
        files: ^(htmd/|tests/|pyproject\.toml)
